### ISSUE TITLE
Investigate a `requiredPermissions` convention on ConditionalFeature

### ISSUE THREAD

**Issue by marcpalmer** [MontanaFlossCo/Flint#48]
Suggested by James Dempsey, this could be used to make features unavailable unless e.g. Photo Library and Camera permissions are granted to the app.

This seems simple enough, but we need to think about what we can do on the other side of it, and whether our checks for status would/should trigger a confirmation alert.

**Comment by hishnash** [comment]
triggering a confirmation alert is an action no `Action`?

since its very bad UX to open an app for the first time and have 10 permission popups i dont think checking should trigger it. 

is there a way for Feature permissions to not be boolean but rather have more info, (in thinking an enum)

so that you can know:
* if it has been requested
* if it is accessible
* if it is not accessible (eg has asked the user already but cant access the feature, so cant show the prompt)
